name: install-nix
on:
  workflow_dispatch:
jobs:
  install-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - run: nix-shell -p nix-info --run "nix-info -m"
